sudo: false
language: ruby
script: rake rspec
rvm:
  - 2.2.2
  - 2.1.2
  - 2.0.0
  - 1.9.3
  - jruby-19mode # JRuby in 1.9 mode
notifications:
  email:
    - pmangiafico@stanford.edu
    - laneymcg@stanford.edu
